on:
  push:
  pull_request:
name: Main workflow
jobs:
  twine_check:
    name: twine check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: snok/install-poetry@v1.3.1
      - run: poetry run pip install twine
      - run: poetry build
      - run: poetry run twine check --strict dist/*

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: snok/install-poetry@v1.3.1
      - run: poetry install
      - run: poetry run mypy .

  pytest:
    name: pytest ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: snok/install-poetry@v1.3.1
      - run: poetry install
      - run: poetry run pytest --cov=mypy_silent --cov-report=xml
      - uses: codecov/codecov-action@v3.1.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
